name: Deploy Web SalaG

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  
jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Acesso EC2
        run: |
            echo "$KEY_G" > webserver.pem && chmod 600 webserver.pem
            ssh -o StrictHostKeyChecking=no -i "webserver.pem" ubuntu@ec2-44-214-35-38.compute-1.amazonaws.com "
                 cd /var/www/html &&
                 git pull "
                 
